### ISSUE TITLE
Strange results YUV410 reference

### ISSUE THREAD

**Issue by pablogil16** [grishnagkh/vqmetric#2]
Hi,

I'm computing the VQM metric with this tool but I get results that in principle doesn't make much sense.

I'm using as a reference a .y4m file with YUV420 format, which according to the "Planned Features" has been already tested. As processed image I'm using a .mp4 file compressed to 100 Kbps and a GOP of 48 seconds (as I planned to split it in 2 second segments). Both are 1 min 30 sec long. At this point I would expect a VQM value close to 1, as the compression is quite high. However, I get the attached .txt file, where the VQM is 0 for most of the segments.

Why is it that the VQM successively decreases to finally reach 0?

[out_vqm_2s.txt](https://github.com/grishnagkh/vqmetric/files/1122182/out_vqm_2s.txt)

**Comment by grishnagkh** [comment]
Hi,

So if I understood correctly, you are feeding a bad quality and expecting bad VQM value?

If so, then the program works correctly and I missed to include an important point from my source code comments in the README: 

According to the VQM paper, a value of 0 is good.
I changed this in order to match SSIM semantics and clipped the VQM output to [0,1] with 0 a bad and 1 a good value.

If not, can you please paste more information (video information & program parameters / call)

**Comment by pablogil16** [comment]
Hi,

Thanks for your quick answer.

Exactly, I'm expecting that. But another thing that also bothers me is the fact that the output is not constant. I mean, taking into account the output switch you mentioned, I get a good quality for the first segments and it gets really bad later. Shouldn't I get a more or less constant VQM as the whole video is compressed at the same quality?

I'm running the program as follows:
> ./vqtool -r reference.y4m -R y4m -p processed.mp4 -P mp4 --vqm out

The following files are the results of running mediainfo for the two video files
[reference_info.txt](https://github.com/grishnagkh/vqmetric/files/1123818/reference_info.txt)
[processed_info.txt](https://github.com/grishnagkh/vqmetric/files/1123820/processed_info.txt)

**Comment by grishnagkh** [comment]
I don't think that VQM should be constant with constant bitrate in general.
Imagine for mostly black scenes  or scenes with little motion, VQM will still be good as it should reflect human perception. 

Do you observe that the video is okay in the first 10 seconds (where VQM says, quality is ok)?

**Comment by pablogil16** [comment]
I've checked the video and the first 10 seconds and they have much less motion than the others.

Thank you so much for your help.
